VULKAN_SDK_PATH = /home/$$USERNAME/libraries/vulkansdk/x86_64
STB_INCLUDE_PATH = /home/$$USERNAME/libraries/stb
TINYOBJ_INCLUDE_PATH = /home/$$USERNAME/libraries/tinyobjloader
NETCDF = /usr/local

CFLAGS = -std=c++17 -I$(VULKAN_SDK_PATH)/include -I$(STB_INCLUDE_PATH) -I$(TINYOBJ_INCLUDE_PATH) -I$(NETCDF)/include -Inetcdfreader/ -O3
LDFLAGS = -L$(VULKAN_SDK_PATH)/lib -L$(NETCDF)/lib ` pkg-config --static --libs glfw3` -lvulkan 

VulkanTest: 
	g++ -Wl,-rpath=/usr/local/lib $(CFLAGS)  -lnetcdf $(LDFLAGS) -o VulkanTest *.cpp  netcdfreader/*.cpp

.PHONY: test clean

test: VulkanTest
	./VulkanTest

run:
	make
	make test

ruin: goliath
	./goliath

goliath: 
	g++ -Wl,-rpath=/usr/local/lib $(CFLAGS) -o goliath goliath.cpp  -lnetcdf $(LDFLAGS)

clean:
	rm -f VulkanTest
	rm -f twod
	rm -f thrid

tidy:
	rm -f goliath

twod:
	g++ -Wl,-rpath=/usr/local/lib -D TWOD $(CFLAGS) -lnetcdf $(LDFLAGS) -o twod netcdfreader/*.cpp *.cpp  
	
twodrun: twod
	./twod

thrid: 
	g++ -Wl,-rpath=/usr/local/lib -D THRID $(CFLAGS) -lnetcdf $(LDFLAGS) -o thrid netcdfreader/*.cpp *.cpp  

thridrun: thrid
	./thrid
